# Generated by Django 4.0.2 on 2022-03-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_date_addedd_subscriber_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='date_added',
            new_name='date_addedd',
        ),
    ]
