# Generated by Django 4.0.2 on 2022-03-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_rename_date_added_subscriber_date_addedd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='date_addedd',
            new_name='date_added',
        ),
    ]
